name: Build sample Add-ons

on:
  # Runs on all PRs, or when called from another workflow.
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: addons-web-sdk/samples/package-lock.json
      - run: npm run build
        working-directory: addons-web-sdk/samples
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: page
          path: addons-web-sdk/samples/dist
          if-no-files-found: error
